#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy

sudo pacman -S openbox obconf firefox file-roller lxappearance-obconf mate-icon-theme-faenza gtk-engine-aurora accountsservice xfce4-mixer xfce4-panel xfdesktop gvfs thunar-archive-plugin thunar-volman xfce4-whiskermenu-plugin networkmanager network-manager-applet python2-xdg lxsession lxterminal leafpad xfce4-settings xfce4-power-manager parcellite ristretto tumbler xfce4-notifyd mate-system-monitor ttf-liberation qtcurve-qt4 zip unzip unrar p7zip wget lynx lightdm lightdm-gtk-greeter ncdu youtube-dl speedtest-cli xorg-xprop wmctrl gstreamer0.10-good-plugins oblogout xdg-user-dirs

mkdir -p ~/.config/openbox
cp -r /etc/xdg/openbox/* ~/.config/openbox
echo "xfce4-panel &" >> ~/.config/openbox/autostart
echo "xfdesktop &" >> ~/.config/openbox/autostart
echo "lxpolkit &" >> ~/.config/openbox/autostart
echo "compton -b &" >> ~/.config/openbox/autostart
echo "xfce4-power-manager &" >> ~/.config/openbox/autostart

sudo cp obx/chrome-avatars/*.png /usr/share/pixmaps/faces
chmod +x obx/aur_ins
obx/aur_ins

xdg-user-dirs-update

sudo systemctl enable accounts-daemon
sudo systemctl enable NetworkManager
sudo systemctl enable lightdm
